// Amostra do feed (mesma estrutura do feed real Atom + Google Shopping).
// Usada como fallback em DESENVOLVIMENTO quando o feed da loja está fora do ar,
// para não travar o trabalho local. Em produção nunca é usada.
export const SAMPLE_FEED = `<?xml version="1.0" encoding="utf-8"?>
<feed xml:lang="pt-br" xmlns="http://www.w3.org/2005/Atom" xmlns:c="http://base.google.com/ns/1.0" xmlns:g="http://base.google.com/ns/1.0">
<title>amostra</title>
<updated>2026-06-24T03:00:00+00:00</updated>
<entry><g:id>1001</g:id><g:title>Botina Don Matuto - Cromo Chocolate - 38</g:title><g:description>Botina em couro legítimo.</g:description><g:link>https://exemplo.com.br/produto/botina-don-matuto/</g:link><g:image_link>https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/sacudidos/media/uploads/produtos/foto/hbpkxhtg/c825ef78-630f-4e19-93b9-4015e07eab49.jpeg</g:image_link><g:additional_image_link>https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/sacudidos/media/uploads/produtos/foto/sgtkwfkz/2a3ad16d-165e-455f-b2fd-d916e0ead29f.jpeg</g:additional_image_link><g:availability>in stock</g:availability><g:price>419.90 BRL</g:price><g:sale_price>419.90 BRL</g:sale_price><c:main_attribute_value>38</c:main_attribute_value><g:color>Chocolate</g:color><g:product_type>Masculino &gt; Calçados &gt; Botas e Botinas</g:product_type><g:size>38</g:size><g:item_group_id>1000</g:item_group_id></entry>
<entry><g:id>1002</g:id><g:title>Botina Don Matuto - Cromo Chocolate - 40</g:title><g:description>Botina em couro legítimo.</g:description><g:link>https://exemplo.com.br/produto/botina-don-matuto/</g:link><g:image_link>https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/sacudidos/media/uploads/produtos/foto/hbpkxhtg/c825ef78-630f-4e19-93b9-4015e07eab49.jpeg</g:image_link><g:availability>in stock</g:availability><g:price>419.90 BRL</g:price><g:sale_price>419.90 BRL</g:sale_price><c:main_attribute_value>40</c:main_attribute_value><g:color>Chocolate</g:color><g:product_type>Masculino &gt; Calçados &gt; Botas e Botinas</g:product_type><g:size>40</g:size><g:item_group_id>1000</g:item_group_id></entry>
<entry><g:id>1003</g:id><g:title>Botina Don Matuto - Cromo Chocolate - 44</g:title><g:description>Botina em couro legítimo.</g:description><g:link>https://exemplo.com.br/produto/botina-don-matuto/</g:link><g:image_link>https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/sacudidos/media/uploads/produtos/foto/hbpkxhtg/c825ef78-630f-4e19-93b9-4015e07eab49.jpeg</g:image_link><g:availability>in stock</g:availability><g:price>419.90 BRL</g:price><g:sale_price>419.90 BRL</g:sale_price><c:main_attribute_value>44</c:main_attribute_value><g:color>Chocolate</g:color><g:product_type>Masculino &gt; Calçados &gt; Botas e Botinas</g:product_type><g:size>44</g:size><g:item_group_id>1000</g:item_group_id></entry>
<entry><g:id>2001</g:id><g:title>Camiseta Sacudido&amp;#x27;s - São Jorge - Preto - P</g:title><g:description>Camiseta 100% algodão.</g:description><g:link>https://exemplo.com.br/produto/camiseta-sao-jorge/</g:link><g:image_link>https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/sacudidos/media/uploads/produtos/foto/ntvnnbdo/d021f10e-3868-4946-86e6-67258a1dcd3c.jpeg</g:image_link><g:availability>in stock</g:availability><g:price>169.90 BRL</g:price><g:sale_price>149.90 BRL</g:sale_price><c:main_attribute_value>P</c:main_attribute_value><g:color>Preto</g:color><g:product_type>Masculino &gt; Camisetas</g:product_type><g:size>P</g:size><g:item_group_id>2000</g:item_group_id></entry>
<entry><g:id>2002</g:id><g:title>Camiseta Sacudido&amp;#x27;s - São Jorge - Preto - M</g:title><g:description>Camiseta 100% algodão.</g:description><g:link>https://exemplo.com.br/produto/camiseta-sao-jorge/</g:link><g:image_link>https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/sacudidos/media/uploads/produtos/foto/ntvnnbdo/d021f10e-3868-4946-86e6-67258a1dcd3c.jpeg</g:image_link><g:availability>in stock</g:availability><g:price>169.90 BRL</g:price><g:sale_price>149.90 BRL</g:sale_price><c:main_attribute_value>M</c:main_attribute_value><g:color>Preto</g:color><g:product_type>Masculino &gt; Camisetas</g:product_type><g:size>M</g:size><g:item_group_id>2000</g:item_group_id></entry>
<entry><g:id>2003</g:id><g:title>Camiseta Sacudido&amp;#x27;s - São Jorge - Preto - G</g:title><g:description>Camiseta 100% algodão.</g:description><g:link>https://exemplo.com.br/produto/camiseta-sao-jorge/</g:link><g:image_link>https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/sacudidos/media/uploads/produtos/foto/ntvnnbdo/d021f10e-3868-4946-86e6-67258a1dcd3c.jpeg</g:image_link><g:availability>out of stock</g:availability><g:price>169.90 BRL</g:price><g:sale_price>149.90 BRL</g:sale_price><c:main_attribute_value>G</c:main_attribute_value><g:color>Preto</g:color><g:product_type>Masculino &gt; Camisetas</g:product_type><g:size>G</g:size><g:item_group_id>2000</g:item_group_id></entry>
<entry><g:id>3001</g:id><g:title>Boné Sacudido&amp;#x27;s - Trucker - Azul</g:title><g:description>Boné trucker ajustável.</g:description><g:link>https://exemplo.com.br/produto/bone-trucker/</g:link><g:image_link>https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/sacudidos/media/uploads/produtos/foto/ujizumzx/354987c3-52f9-4540-b4bf-8202dd5722b7.jpeg</g:image_link><g:availability>in stock</g:availability><g:price>99.90 BRL</g:price><g:sale_price>99.90 BRL</g:sale_price><c:main_attribute_value></c:main_attribute_value><g:color>Azul</g:color><g:product_type>Acessórios &gt; Bonés</g:product_type><g:size></g:size><g:item_group_id>3000</g:item_group_id></entry>
<entry><g:id>4001</g:id><g:title>Chapéu de Couro - Café - 56</g:title><g:description>Chapéu de couro legítimo.</g:description><g:link>https://exemplo.com.br/produto/chapeu-couro/</g:link><g:image_link>https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/sacudidos/media/uploads/produtos/foto/onyuasss/e2317113-60c4-45a5-8589-181f00b14d68.jpeg</g:image_link><g:availability>in stock</g:availability><g:price>259.90 BRL</g:price><g:sale_price>259.90 BRL</g:sale_price><c:main_attribute_value>56</c:main_attribute_value><g:color>Café</g:color><g:product_type>Acessórios &gt; Chapéus</g:product_type><g:size>56</g:size><g:item_group_id>4000</g:item_group_id></entry>
<entry><g:id>4002</g:id><g:title>Chapéu de Couro - Café - 58</g:title><g:description>Chapéu de couro legítimo.</g:description><g:link>https://exemplo.com.br/produto/chapeu-couro/</g:link><g:image_link>https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/sacudidos/media/uploads/produtos/foto/onyuasss/e2317113-60c4-45a5-8589-181f00b14d68.jpeg</g:image_link><g:availability>in stock</g:availability><g:price>259.90 BRL</g:price><g:sale_price>259.90 BRL</g:sale_price><c:main_attribute_value>58</c:main_attribute_value><g:color>Café</g:color><g:product_type>Acessórios &gt; Chapéus</g:product_type><g:size>58</g:size><g:item_group_id>4000</g:item_group_id></entry>
</feed>`;
